#!/usr/bin/env bash
#
# mayhem/build.sh — build the z88dk z80asm fuzz target (+ a clean test build for the oracle).
#
# The Mayhem target is the z80asm assembler binary itself, driven on a file input (@@). z88dk ships
# no LLVMFuzzerTestOneInput harness — Mayhem fuzzes the whole CLI on an input .asm file, and the
# sanitized binary IS its own run-once reproducer. So there is no LIB_FUZZING_ENGINE link and no
# separate *-standalone driver here; we build the assembler twice:
#   (1) SANITIZED (ASan+UBSan, halting) + DWARF<4  -> /mayhem/z80asm   (the fuzz/repro target)
#   (2) NORMAL flags (independent, clean build) -> /mayhem/bin/z80asm-test (the oracle binary)
#
# Env contract comes from the base image (see the template header): CC/CXX, SANITIZER_FLAGS,
# DEBUG_FLAGS, MAYHEM_JOBS, SRC=/mayhem. Keep the upstream tree untouched (additive).
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' (empty) — it must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}"
: "${MAYHEM_JOBS:=$(nproc)}"
: "${COVERAGE_FLAGS=}"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX MAYHEM_JOBS COVERAGE_FLAGS

# z88dk's hand-rolled OO layer (the "class"/CLASS macros in src/c/*) casts struct pointers and calls
# object destructors through generic function pointers. Under halting UBSan that trips two benign,
# UBIQUITOUS checks on essentially every input — `alignment` and `function` — aborting before the
# fuzzer can explore. Relax only those checks when UBSan is active (ASan + the rest of UBSan stay
# halting). Cohort precedent: genometools `gt` (function), wla-dx (detect_leaks=0 for arena-by-exit).

SRC="${SRC:-/mayhem}"
cd "$SRC"

# config.h is normally generated by the top-level Makefile from git metadata. Generate it directly
# (no network / no git needed) so the build is air-gapped and idempotent.
mkdir -p bin
if [ ! -f src/config.h ]; then
  {
    echo '#define PREFIX "/mayhem"'
    echo '#define BINDIR "/mayhem/bin"'
    echo '#define UNIX 1'
    echo '#define Z88DK_VERSION "mayhem-mayhem-2.4"'
  } > src/config.h
fi

ASMDIR="$SRC/src/z80asm"

FUZZ_FLAGS="$SANITIZER_FLAGS"
case "$SANITIZER_FLAGS" in *undefined*)
  FUZZ_FLAGS="$SANITIZER_FLAGS -fno-sanitize=function -fno-sanitize=alignment"
  ;;
esac

ASAN_OPTS_O="$SRC/mayhem/asan_options.c"

# ---- (1) SANITIZED fuzz/repro build --------------------------------------------------------------
# Instrument the project itself with $SANITIZER_FLAGS so Mayhem gets edge coverage (integrated CLI
# pattern: wla-dx, genometools — NOT AFL; AFL persistent mode records 0 edges on fork-exec CLIs).
make -C "$ASMDIR" clean >/dev/null 2>&1 || true
make -C "$ASMDIR" -j"$MAYHEM_JOBS" z88dk-z80asm \
  CC="$CC" CXX="$CXX" \
  CFLAGS="$FUZZ_FLAGS $DEBUG_FLAGS" \
  CXXFLAGS="$FUZZ_FLAGS $DEBUG_FLAGS" \
  LDFLAGS="$FUZZ_FLAGS $DEBUG_FLAGS -rdynamic $ASAN_OPTS_O"
cp "$ASMDIR/z88dk-z80asm" "$SRC/z80asm"

# ---- (2) NORMAL (clean) build for the functional oracle ------------------------------------------
# Independent of the sanitized objects above → make clean first, rebuild with the project's normal
# flags (plus optional $COVERAGE_FLAGS, empty by default). This is what mayhem/test.sh RUNS.
make -C "$ASMDIR" clean >/dev/null 2>&1 || true
make -C "$ASMDIR" -j"$MAYHEM_JOBS" z88dk-z80asm \
  CC="$CC" CXX="$CXX" \
  CFLAGS="$COVERAGE_FLAGS" \
  CXXFLAGS="$COVERAGE_FLAGS" \
  LDFLAGS="$COVERAGE_FLAGS -rdynamic"
cp "$ASMDIR/z88dk-z80asm" "$SRC/bin/z80asm-test"

echo "build.sh: built /mayhem/z80asm (sanitized), /mayhem/bin/z80asm-test (oracle)"
